[ `go build -x -v hello` | done: 820.12ms ]
	WORK=C:\Users\Yao\AppData\Local\Temp\go-build740943458
	hello/utils
	mkdir -p $WORK\hello\utils\_obj\
	mkdir -p $WORK\hello\
	cd D:\workspace\work4Git\Hello_Go\src\hello\utils
	"D:\\server\\go\\1.8\\pkg\\tool\\windows_amd64\\compile.exe" -o "C:\\Users\\Yao\\AppData\\Local\\Temp\\go-build740943458\\hello\\utils.a" -trimpath "C:\\Users\\Yao\\AppData\\Local\\Temp\\go-build740943458" -p hello/utils -complete -buildid 883bca5c8fc98586612c759ca003ec26cbcff2e8 -D _/D_/workspace/work4Git/Hello_Go/src/hello/utils -I "C:\\Users\\Yao\\AppData\\Local\\Temp\\go-build740943458" -pack "D:\\workspace\\work4Git\\Hello_Go\\src\\hello\\utils\\funcCallsFunction.go" "D:\\workspace\\work4Git\\Hello_Go\\src\\hello\\utils\\globalScope.go" "D:\\workspace\\work4Git\\Hello_Go\\src\\hello\\utils\\helloArray.go" "D:\\workspace\\work4Git\\Hello_Go\\src\\hello\\utils\\helloBig.go" "D:\\workspace\\work4Git\\Hello_Go\\src\\hello\\utils\\helloBytes.go" "D:\\workspace\\work4Git\\Hello_Go\\src\\hello\\utils\\helloClosureFunc.go" "D:\\workspace\\work4Git\\Hello_Go\\src\\hello\\utils\\helloControl.go" "D:\\workspace\\work4Git\\Hello_Go\\src\\hello\\utils\\helloDefer.go" "D:\\workspace\\work4Git\\Hello_Go\\src\\hello\\utils\\helloFunc.go" "D:\\workspace\\work4Git\\Hello_Go\\src\\hello\\utils\\helloFuncFunc.go" "D:\\workspace\\work4Git\\Hello_Go\\src\\hello\\utils\\helloInt.go" "D:\\workspace\\work4Git\\Hello_Go\\src\\hello\\utils\\helloMap.go" "D:\\workspace\\work4Git\\Hello_Go\\src\\hello\\utils\\helloMultiReturn.go" "D:\\workspace\\work4Git\\Hello_Go\\src\\hello\\utils\\helloPoint.go" "D:\\workspace\\work4Git\\Hello_Go\\src\\hello\\utils\\helloRand.go" "D:\\workspace\\work4Git\\Hello_Go\\src\\hello\\utils\\helloRecursiveFunc.go" "D:\\workspace\\work4Git\\Hello_Go\\src\\hello\\utils\\helloRegexp.go" "D:\\workspace\\work4Git\\Hello_Go\\src\\hello\\utils\\helloSlice.go" "D:\\workspace\\work4Git\\Hello_Go\\src\\hello\\utils\\helloSort.go" "D:\\workspace\\work4Git\\Hello_Go\\src\\hello\\utils\\helloStrconv.go" "D:\\workspace\\work4Git\\Hello_Go\\src\\hello\\utils\\helloString.go" "D:\\workspace\\work4Git\\Hello_Go\\src\\hello\\utils\\helloStrings.go" "D:\\workspace\\work4Git\\Hello_Go\\src\\hello\\utils\\helloSync.go" "D:\\workspace\\work4Git\\Hello_Go\\src\\hello\\utils\\helloTime.go" "D:\\workspace\\work4Git\\Hello_Go\\src\\hello\\utils\\helloUnicode.go" "D:\\workspace\\work4Git\\Hello_Go\\src\\hello\\utils\\helloVar.go" "D:\\workspace\\work4Git\\Hello_Go\\src\\hello\\utils\\helloWorld.go" "D:\\workspace\\work4Git\\Hello_Go\\src\\hello\\utils\\localScope.go"
	hello
	mkdir -p $WORK\hello\_obj\
	mkdir -p $WORK\hello\_obj\exe\
	cd D:\workspace\work4Git\Hello_Go\src\hello
	"D:\\server\\go\\1.8\\pkg\\tool\\windows_amd64\\compile.exe" -o "C:\\Users\\Yao\\AppData\\Local\\Temp\\go-build740943458\\hello.a" -trimpath "C:\\Users\\Yao\\AppData\\Local\\Temp\\go-build740943458" -p main -complete -buildid d7951250569beb2b10dfaab3f800fffe4b8b6575 -D _/D_/workspace/work4Git/Hello_Go/src/hello -I "C:\\Users\\Yao\\AppData\\Local\\Temp\\go-build740943458" -I "D:\\workspace\\work4Git\\Hello_Go\\pkg\\windows_amd64" -pack "D:\\workspace\\work4Git\\Hello_Go\\src\\hello\\helloPrint.go"
	cd .
	"D:\\server\\go\\1.8\\pkg\\tool\\windows_amd64\\link.exe" -o "C:\\Users\\Yao\\AppData\\Local\\Temp\\go-build740943458\\hello\\_obj\\exe\\a.out.exe" -L "C:\\Users\\Yao\\AppData\\Local\\Temp\\go-build740943458" -L "D:\\workspace\\work4Git\\Hello_Go\\pkg\\windows_amd64" -extld=gcc -buildmode=exe -buildid=d7951250569beb2b10dfaab3f800fffe4b8b6575 "C:\\Users\\Yao\\AppData\\Local\\Temp\\go-build740943458\\hello.a"
	cp $WORK\hello\_obj\exe\a.out.exe hello.exe